name: Build and deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        uses: actions/setup-node@v2
        with:
          node-version: "25"

      - run: npm install --global sass

      - name: Build theme
        run: sass hazels-theme.theme.sass .dist/hazels-theme.theme.css

      - name: Copy manifests
        run: |
          cp cumcord_theme.json .dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: ".dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
